### ISSUE TITLE
部署到服务器时  配置监测站点请求   /server/upLog 404

### ISSUE THREAD

**Issue by xiaomei991** [a597873885/webfunny-servers#2]
![image](https://user-images.githubusercontent.com/20355401/65831031-8cdb0f00-e2e7-11e9-80c6-03d44f8fc0e6.png)
这个在生成探针时，探针代码里面是不是要改些东西？像下面这里的代码
![image](https://user-images.githubusercontent.com/20355401/65831075-138fec00-e2e8-11e9-905a-4594122b7370.png)

**Comment by a597873885** [comment]
@xiaomei991 是需要配置的。
![image](https://user-images.githubusercontent.com/26519165/65832323-8737f600-e2f4-11e9-8167-9f2d0d4d1bb3.png)

**Comment by xiaomei991** [comment]
@a597873885 这边我改了，改成我服务器上部署的
![image](https://user-images.githubusercontent.com/20355401/65832589-4fcb4880-e2f8-11e9-8497-0276259fdcc1.png)
![image](https://user-images.githubusercontent.com/20355401/65832617-b8b2c080-e2f8-11e9-86c3-10b8e3c1bec0.png)
![image](https://user-images.githubusercontent.com/20355401/65832624-ce27ea80-e2f8-11e9-9f45-9f19321c3361.png)
我自己手动改了下，再集成到前端项目里面
![image](https://user-images.githubusercontent.com/20355401/65832641-0f1fff00-e2f9-11e9-8396-17d572b5f444.png)
中间自己点击测了几次，错误也测了一下，不过好像都没有监控到，一直都是空的
![image](https://user-images.githubusercontent.com/20355401/65832657-47bfd880-e2f9-11e9-8791-9e3020d803fd.png)

**Comment by xiaomei991** [comment]
@a597873885 
![image](https://user-images.githubusercontent.com/20355401/65832842-172d6e00-e2fc-11e9-97cb-3bae4fcd21bc.png)

**Comment by a597873885** [comment]
@xiaomei991  为什么要手动改呢，有没有按照部署步骤中的5，6两步进行操作？

**Comment by a597873885** [comment]
@xiaomei991 我找到原因了，稍等一下，我做下调整

**Comment by a597873885** [comment]
@xiaomei991  请重新创建新应用，部署上去，三十秒内会有数据上传，感谢你的反馈。

**Comment by xiaomei991** [comment]
好，我刚才也有东西配错了，不过还是要手动改下配针的地址才可以上传日志，不过这个页面打开会上传日志吗？还是只有有操作或者错误的时候才上传

**Comment by xiaomei991** [comment]
@a597873885 好，我刚才也有东西配错了，不过还是要手动改下配针的地址才可以上传日志，不过这个页面打开会上传日志吗？还是只有有操作或者错误的时候才上传

**Comment by a597873885** [comment]
@xiaomei991 部分数据是实时表现的，但是分析数据一般都会在半个小时内有反馈

**Comment by xiaomei991** [comment]
@a597873885 很棒，谢谢

**Comment by xiaomei991** [comment]
@a597873885 等你那个改完，麻烦告知下，我重新部署下

**Comment by a597873885** [comment]
已经改完了





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiaomei991 <notifications@github.com&gt;
发送时间: 2019年9月29日 21:37
收件人: a597873885/webfunny-servers <webfunny-servers@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny-servers] 部署到服务器时  配置监测站点请求   /server/upLog 404 (#2)




@a597873885 等你那个改完，麻烦告知下，我重新部署下

**Comment by xiaomei991** [comment]
是重新拉webfunny-servers这个项目的代码吗，好像没看到更新

**Comment by xiaomei991** [comment]
@a826604005 这个项目里面的代码会更新吗

**Comment by a597873885** [comment]
新建应用就行，不用拉代码

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiaomei991 <notifications@github.com&gt;
发送时间: 2019年9月29日 21:42
收件人: a597873885/webfunny-servers <webfunny-servers@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny-servers] 部署到服务器时  配置监测站点请求   /server/upLog 404 (#2)




是重新拉webfunny-servers这个项目的代码吗，好像没看到更新

**Comment by xiaomei991** [comment]
@a597873885 好的，谢谢

**Comment by xiaomei991** [comment]
@a597873885 我早上看了下，有很多接口请求404了，重启一下服务又好了，请问这是啥问题

**Comment by a597873885** [comment]
这个我忘了在文档了说了，为了提高查询效率，数据库是做分表的，我的做法是用jenkins定时重启服务就会生成新的一套数据库表，暂时我还没有找到好的方法用代码重新生成数据库表，这个问题我会尽快找到解决办法。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiaomei991 <notifications@github.com&gt;
发送时间: 2019年9月30日 08:57
收件人: a597873885/webfunny-servers <webfunny-servers@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny-servers] 部署到服务器时  配置监测站点请求   /server/upLog 404 (#2)




@a597873885 我早上看了下，有很多接口请求404了，重启一下服务又好了，请问这是啥问题

**Comment by xiaomei991** [comment]
@a597873885 好的，那我去看看你说的jenkins定时重启服务

**Comment by xiaomei991** [comment]
@a597873885 对了，你这边是什么时间点会进行分表的

**Comment by a597873885** [comment]
凌晨0点



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiaomei991 <notifications@github.com&gt;
发送时间: 2019年9月30日 09:09
收件人: a597873885/webfunny-servers <webfunny-servers@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny-servers] 部署到服务器时  配置监测站点请求   /server/upLog 404 (#2)




@a597873885 对了，你这边是什么时间点会进行分表的

**Comment by xiaomei991** [comment]
获取前几天的javascriptErrorDetail是不是有问题，好像那个页面只能获取当天的，如果当天没有那个错误，页面没有数据
![image](https://user-images.githubusercontent.com/20355401/66360823-08575300-e9af-11e9-8d2f-06bfe7539620.png)
![image](https://user-images.githubusercontent.com/20355401/66360810-fd9cbe00-e9ae-11e9-91cc-bca6dc763e45.png)
这个错误当天有数据，点进去就会显示当天数据，点另外的数据获取不到，是不是分表导致的问题

**Comment by a597873885** [comment]
目前是这样的，因为详情要查询的东西太多，所以就只查当天的，如果当天没有这个错误，就不需要再关注了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiaomei991 <notifications@github.com&gt;
发送时间: 2019年10月8日 09:37
收件人: a597873885/webfunny-servers <webfunny-servers@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny-servers] 部署到服务器时  配置监测站点请求   /server/upLog 404 (#2)




获取前几天的javascriptErrorDetail是不是有问题，好像那个页面只能获取当天的，如果当天没有那个错误，页面没有数据
 
 
 这个错误当天有数据，点进去就会显示当天数据，点另外的数据获取不到，是不是分表导致的问题
